name: CD

on: 
  push:
    branches: 
      - develop

jobs:
  build:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1!
    - name: SSH Commands
      uses: appleboy/ssh-action@v0.0.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami
